apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: heapster-heapster
  name: heapster
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: heapster-heapster