apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus-alertmanager
    release: prometheus-alertmanager
  name: prometheus-alertmanager
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: "efs"
  #volumeName: PV_NAME
