apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus-server
    release: prometheus-server
  name: prometheus-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: "efs"
  #volumeName: PV_NAME
