apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: metrics-server