apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana
    release: grafana
  name: grafana
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "efs"
  #volumeName: PV_NAME
