apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: cert-manager
  name: cert-manager
  namespace: kube-ingress
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: cert-manager